### ISSUE TITLE
Please add this game

### ISSUE THREAD

**Issue by nekomancer97** [hobby-grade/Nintendo-Switch-Discord-Status#103]
Coffee Talk is my favorite cozy game on Switch, please add. I would be so grateful!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.3

*Thank you for checking out the project, reach out if you have any more suggestions!*
