### ISSUE TITLE
can you please add Sky: Children of the Light

### ISSUE THREAD

**Issue by LesterF9F** [hobby-grade/Nintendo-Switch-Discord-Status#106]
I play it with my friends and would be cool if I can show it on my status

Game name is: Sky: Children of the Light

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.3

*Thank you for checking out the project, reach out if you have any more suggestions!*
