### ISSUE TITLE
Missing Title: Star Wars Republic Commando

### ISSUE THREAD

**Issue by MikeVPat** [hobby-grade/Nintendo-Switch-Discord-Status#107]
Could you please add Star Wars: Republic Commando to the games list? Thanks!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.3

*Thank you for checking out the project, reach out if you have any more suggestions!*
