### ISSUE TITLE
Missing: Could you add Overwatch 2, thank you!

### ISSUE THREAD

**Issue by venotoxious** [hobby-grade/Nintendo-Switch-Discord-Status#108]
Could you please add Overwatch 2, thank you!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.3

*Thank you for checking out the project, reach out if you have any more suggestions!*
