### ISSUE TITLE
game

### ISSUE THREAD

**Issue by valeisooocool** [hobby-grade/Nintendo-Switch-Discord-Status#112]
Can you add Danganronpa : Trigger Happy Havoc , Danganronpa 2 : Goodbye Despair, and Danganronpa V3: Killling Harmony? Thanks!

**Comment by RandomCrapzs** [comment]
Game request: Just Dance 2023. Thanks

**Comment by RandomCrapzs** [comment]
Game request: Just Dance 2023. Thanks

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
