### ISSUE TITLE
Game Suggestion

### ISSUE THREAD

**Issue by RougeEmperor** [hobby-grade/Nintendo-Switch-Discord-Status#115]
Ninjala, Kirby dream buffet and Super Kirby Clash

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
