### ISSUE TITLE
Fire Emblem Engage!!

### ISSUE THREAD

**Issue by Nerdextrous** [hobby-grade/Nintendo-Switch-Discord-Status#118]
Any chance Fire Emblem Engage could be added by the release on the 20th?

Thank you!!! 😁

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
