### ISSUE TITLE
Game Suggestion

### ISSUE THREAD

**Issue by Trperson** [hobby-grade/Nintendo-Switch-Discord-Status#120]
Could you add the game "asphalt legends"? Please. I think that would be awesome! Ty

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
