### ISSUE TITLE
32-bit operating system

### ISSUE THREAD

**Issue by Johan23t** [hobby-grade/Nintendo-Switch-Discord-Status#121]
Is it possible to make a version that can run on 32-bit operating systems?

**Comment by hobby-grade** [comment]
I have not tested the ability to run on 32-bit OSes, what are you running this on that requires a 32-bit application?

**Comment by Johan23t** [comment]
The only thing I have at the moment is a DELL Latitude E5450 Laptop. It's only able to run 32-bit programs.

**Comment by hobby-grade** [comment]
Unfortunately, I do not currently have the resources to format this for a 32-bit OS. I would look into running a 64-bit version of your preferred OS in order to increase compatibility with modern applications.
