### ISSUE TITLE
Game Suggestions

### ISSUE THREAD

**Issue by athens009** [hobby-grade/Nintendo-Switch-Discord-Status#122]
Any chance you could add two of these games:

Persona 3 Portable
Persona 4 Golden

Thanks!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
