### ISSUE TITLE
Game suggestion

### ISSUE THREAD

**Issue by unreligious** [hobby-grade/Nintendo-Switch-Discord-Status#125]
Please add all of the Kingdom Hearts Cloud Versions!
Also Persona 3 Portable and 4 Golden

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
