### ISSUE TITLE
Game Suggestions

### ISSUE THREAD

**Issue by Vauxten** [hobby-grade/Nintendo-Switch-Discord-Status#127]
All Jackbox Party Packs list:
w/extra game: Thief Simulator
The Jackbox Party Pack
The Jackbox Party Pack 2
The Jackbox Party Pack 3
The Jackbox Party Pack 4
The Jackbox Party Pack 5
The Jackbox Party Pack 6
The Jackbox Party Pack 7
The Jackbox Party Pack 8
The Jackbox Party Pack 9

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
