### ISSUE TITLE
New Game Suggestion

### ISSUE THREAD

**Issue by WispySkies02** [hobby-grade/Nintendo-Switch-Discord-Status#130]
I was wondering if NASCAR Heat Ultimate Edition + and NASCAR Rivals could be added to the list

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
