### ISSUE TITLE
Game suggestions:

### ISSUE THREAD

**Issue by Vauxten** [hobby-grade/Nintendo-Switch-Discord-Status#137]
last update: pov: all the jackbox games fans crying rn
Add Jackbox Party Packs from 1 to 9

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
