### ISSUE TITLE
New game suggestion

### ISSUE THREAD

**Issue by Theniaa** [hobby-grade/Nintendo-Switch-Discord-Status#138]
Hello! Ive seen someone else suggest this game as well but i would like to ask if you could please add Fire Emblem Engage?

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
