### ISSUE TITLE
New Game Addition

### ISSUE THREAD

**Issue by Picugaming39** [hobby-grade/Nintendo-Switch-Discord-Status#139]
One game that isn't actually in the program is .Hack//G.U. Last Recode

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
