### ISSUE TITLE
New game suggestions!

### ISSUE THREAD

**Issue by CherryBunz** [hobby-grade/Nintendo-Switch-Discord-Status#140]
Definitely not expecting all three but wanted to suggest:

- ~~Project Diva Mega Mix~~ <- already in the application
- Saints Row 3 or 4
- South Park: The Fractured But Whole

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
