### ISSUE TITLE
New Game Suggestion

### ISSUE THREAD

**Issue by Mykurr** [hobby-grade/Nintendo-Switch-Discord-Status#142]
Since I'm binging the trails franchise it'd be great to add the following games:

- The Legend of Heroes: Trails from Zero
- The Legend of Heroes: Trails to Azure
- The Legend of Heroes: Cold Steel III
- The Legend of Heroes: Cold Steel IV

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
