### ISSUE TITLE
Can you guys please add these games?

### ISSUE THREAD

**Issue by Jochoa149** [hobby-grade/Nintendo-Switch-Discord-Status#143]
~~Nintendo Switch Sports~~
~~Dreamlight Valley~~
~~Just Dance 2020-2023~~
Spongebob Squarepants Battle for Bikini Bottom Rehydrated
Uno
Nickoleadeon Kart Racers
~~Miitopia~~

**Comment by hobby-grade** [comment]
Nintendo Switch Sports is already in the application, and the Just Dance games are being changed to just the name "Just Dance" with no specific year due to them taking up additional space wtih each year. The other games will be added.

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
