### ISSUE TITLE
New Games

### ISSUE THREAD

**Issue by dotwavisito** [hobby-grade/Nintendo-Switch-Discord-Status#145]
- Fire Emblem Engage
- Megaman Battle Network Legacy Collection Vol. 1
- Megaman Battle Network Legacy Collection Vol. 2
- Cult of the Lamb
- Bayonetta Origins: Cereza and the Lost Demon

Upcoming:
- Advanced Wars 1+2: Re-Boot Camp
- The Legend of Zelda: Tears of the Kingdom
- Front Misson 1st
- ONI: Road to be the Mightiest Oni

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
