### ISSUE TITLE
Game Adddition

### ISSUE THREAD

**Issue by awokeyam** [hobby-grade/Nintendo-Switch-Discord-Status#146]
Could you please add

Tales of Symphonia
Tales of Vesperia

Thank you!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
