### ISSUE TITLE
Linux Access

### ISSUE THREAD

**Issue by slxshrx** [hobby-grade/Nintendo-Switch-Discord-Status#174]
heya, i wanted to ask:  which file should i use if i'm using linux in the latest update?

**Comment by cYbercOsmOnauT** [comment]
Clone the repo.
Go to the main directory with a shell.
sudo npm install (try without sudo first)
npm start

that's it

**Comment by hobby-grade** [comment]
Alternatively, use the AppImage file in "Releases".
