### ISSUE TITLE
Doesn't seem to change my online status (imac)

### ISSUE THREAD

**Issue by AkiLyka** [hobby-grade/Nintendo-Switch-Discord-Status#177]
Hello! got your app bc the NSO-RPC wasn't working for me. figured yours would be easier. I downloaded it via the DMG file. I put in a test game (Mario Kart) and clicked "submit" and nothing changes, friends even say my status just says "Online"

Discord is up to date, your app is the latest version, my imac is 10.15.7. I have account activity all are ON. I even checked servers as suggested in a similar post to mine. it only says "Online"

**Comment by hobby-grade** [comment]
Hello, 

Did you already try restarting your computer/discord?: (Y/N)

**Comment by AkiLyka** [comment]
> Hello,
> 
> Did you already try restarting your computer/discord?: (Y/N)

A restart of Discord didn't fix it. However, A full restart of the computer seemed to fix it thanks! I didn't even think of trying to restart my computer.

**Comment by hobby-grade** [comment]
I'm glad it works now.
