### ISSUE TITLE
macOS: Not running, needs update

### ISSUE THREAD

**Issue by m0urao** [hobby-grade/Nintendo-Switch-Discord-Status#196]
Hi, I can't run this on macOS because Apple cannot check for malicious software. Any updates on when this will be solved?

- macOS version: 14.4 

![Screenshot 2024-03-26 at 10 23 26](https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/assets/91987141/738053e5-2c88-4995-9845-ef11304ac1f6)

**Comment by cYbercOsmOnauT** [comment]
Did you run it for the first time by doubleclicking it? Right click and choose "Open". Then normally you can still start it up.

**Comment by m0urao** [comment]
Oh yeah lol that solves it. Thanks!
