### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by JBluesword** [hobby-grade/Nintendo-Switch-Discord-Status#2]
Link for installation for windows in readme file is broken. I get a 404 error every time I click on it. 
The following link doesn't work either
https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases

**Comment by hobby-grade** [comment]
Sorry for the delay, I have posted a first release for this and additionally updated the link in the readme.

**Comment by JBluesword** [comment]
Link works
