### ISSUE TITLE
Is there a button somewhere to exit the game?

### ISSUE THREAD

**Issue by SmilRi** [hobby-grade/Nintendo-Switch-Discord-Status#23]
Is there a button somewhere to exit the game?

**Comment by hobby-grade** [comment]
Yes, click the button that reads "Idle".

**Comment by hobby-grade** [comment]
What happens when you click on the button? What would you like to happen when you press the button?

**Comment by hobby-grade** [comment]
I'm going to assume by your lack of response that this "issue" has been resolved.
