### ISSUE TITLE
Useless with discord online

### ISSUE THREAD

**Issue by DownLoude** [hobby-grade/Nintendo-Switch-Discord-Status#27]
Does not interface with discord online.

**Comment by hobby-grade** [comment]
If you are referring to using Discord in your browser, then of course not; No applications interface with Discord via the browser. You will need to be using the Discord application on your computer, as I stated in the prerequisites section on the readme. 

> All you need is a high tolerance for bad UI and the [Discord App](https://discordapp.com/) installed to the same machine.
