### ISSUE TITLE
Game Addition

### ISSUE THREAD

**Issue by py-uu** [hobby-grade/Nintendo-Switch-Discord-Status#28]
Can you add the game Sushi Striker: The Way of Sushido? And Super Mario 3D: All Stars?  EDIT: Can you also add the game Miitopia? Thanks so much!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/0.9.6.4
