### ISSUE TITLE
Game addition

### ISSUE THREAD

**Issue by dkuester** [hobby-grade/Nintendo-Switch-Discord-Status#30]
Can you please add the Assassin's Creed games for the Switch:

- Assassin's Creed: The Ezio Collection
- Assassin's Creed III Remastered
- Assassin's Creed: The Rebel Collection

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/0.9.6.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
