### ISSUE TITLE
"Little Nightmare I & II" Missing

### ISSUE THREAD

**Issue by Bougy9** [hobby-grade/Nintendo-Switch-Discord-Status#32]
Hello, can you add Little Nightmare I & II, it will be great ^^

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/0.9.6.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
