### ISSUE TITLE
Can you add Kirby and the Forgotten Land to this please?

### ISSUE THREAD

**Issue by potato451e** [hobby-grade/Nintendo-Switch-Discord-Status#35]

**Comment by potato451e** [comment]
And if it's not too much to ask, please add an icon for Super Mario 3D World + Bowser's Fury (thank you, much appreciated!!)

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/0.9.6.5

I don't know why there wasn't an icon before, but I should have added one now, test it out and let me know if it works!

*Thank you for checking out the project, reach out if you have any more suggestions!*
