### ISSUE TITLE
Could you please add "Groove Coaster: Wai Wai Party!!!!" to the list?

### ISSUE THREAD

**Issue by CloudyObsession** [hobby-grade/Nintendo-Switch-Discord-Status#36]
I know there is currently a limitation to the amount of games that can be displayed so I understand if you don't want to add this one as it is a bit niche, but I would certainly appreciate it if you could!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/0.9.6.5

we welcome all games here!

*Thank you for checking out the project, reach out if you have any more suggestions!*
