### ISSUE TITLE
Some Games to Add

### ISSUE THREAD

**Issue by alchemical-Apocalypse** [hobby-grade/Nintendo-Switch-Discord-Status#37]
just found some games that weren't already on the list that i think could potentially be worth making a spot for, provided there's room of course:

- Xenoblade Chronicles: Definitive Edition
- The World Ends with You: Final Remix
- NEO: The World Ends with You 
- i know others have mentioned it already, but Kirby and the Forgotten Land
- Shin Megami Tensei III Nocturne: HD Remaster
thank you so much!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/0.9.6.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
