### ISSUE TITLE
Game Additions

### ISSUE THREAD

**Issue by dotwavisito** [hobby-grade/Nintendo-Switch-Discord-Status#39]
Hello, first off, thank you for taking it upon yourself to keep adding games to this app. I was so bummed to see the original have such a short list.

I have seen requests for Kirby and the Forgotten Land as well as Triangle Strategy and echo those!

In addition I would like to kindly request as many of these games in my collection as possible, I know some may be niche titles but they would be greatly appreciated:

- Hotline Miami Collection
- Castlevania Advance Collection
- Hades
- Dead Cells
- Furi
- Shin Megami Tensei III Nocturne HD Remaster
- Mega Max X Legacy Collection
- Mega Man X Legacy Collection 2
- MEGAMAN ZERO/ZX LEGACY COLLECTION
- Immortals Fenyx Rising
- Star Wars Jedi Knight: Jedi Academy
- Star Wars Jedi Knight: Jedi Outcast

I know this list is long and easy for me to give not knowing the work necessary to add these to new releases, but thank you again!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/0.9.6.5

*Thank you for checking out the project, reach out if you have any more suggestions!*
