### ISSUE TITLE
New Game Additions

### ISSUE THREAD

**Issue by dotwavisito** [hobby-grade/Nintendo-Switch-Discord-Status#45]
Got two more games I'd like to see added when you can!
- Chrono Cross: The Radical Dreamers Edition
- Disco Elysium - The Final Cut

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/1.0.1

*Thank you for checking out the project, reach out if you have any more suggestions!*
