### ISSUE TITLE
Could you add these games?

### ISSUE THREAD

**Issue by Rempai** [hobby-grade/Nintendo-Switch-Discord-Status#5]
Hi could you maybe add: 
- Pokemon Brilliant Diamond
- Pokemon Shining Pearl
- Legend of Zelda Skyward Sword
- Mario Party Superstars
- Wario Ware
- Metroid Dread
- Monster Hunter Rise
- New Pokemon Snap
- Puyo Puyo Tetris 2
- 51 worldwide games
- Hatsune Miku: Project DIVA Mega Mix
- Taiko no Tatsujin: Drum 'n Fun!
- Taiko no Tatsujin Rhytmic Adventure 1 & 2
- Trials of Mana
- Undertale
- Deltarune Chapter 1 & 2
- Nintendo 64 Online
Alright I know I'm asking for quite a lot and I'm sorry, I've put them in order of how much I want them added or not. If you need anything like resources or help I would love to help. Maybe it's possible because of the 150 limit to add a way for people to make their own version of this system so they can just add their own list of games in their own version, that way once you are limited for the resources like images people don't constantly have to ask for new games but can make their own version to work with their gaming list.

**Comment by hobby-grade** [comment]
Hello, 

I have added these games in the 0.9.0 update that I just published: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/0.9.0

I have found out that discord increased the art asset limit to 300, so the list is not going to fill up nearly as quickly as it was before. If you'd like to make your own version of the application, you will need to make a Discord developer application to host your own art assets, and you'd need to make sure that the names of the files can be referenced correctly in the gameslist.json file. This can be done, but to have each person who ever would like to use the app do this and maintain their own build is not very user friendly. 

I appreciate you taking a look at the application, and for providing feedback!
