### ISSUE TITLE
One More Addition

### ISSUE THREAD

**Issue by alchemical-Apocalypse** [hobby-grade/Nintendo-Switch-Discord-Status#50]
as the title says, i just had one addition to suggest

- KINGDOM HEARTS Melody of Memory

thank you for all of your hard work!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/1.0.2

*Thank you for checking out the project, reach out if you have any more suggestions!*
