### ISSUE TITLE
One Addition

### ISSUE THREAD

**Issue by Onyi21** [hobby-grade/Nintendo-Switch-Discord-Status#52]
If y'all could add Night in the Woods, that would be awesome. 
Appreciate the hard work!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/1.0.2

*Thank you for checking out the project, reach out if you have any more suggestions!*
