### ISSUE TITLE
[Enhancement] Add Newly Released Title

### ISSUE THREAD

**Issue by julvignola** [hobby-grade/Nintendo-Switch-Discord-Status#53]
Hi! ~

I was wondering if you could add the newly released "Nintendo Switch Sports" title to the games list. 

Thank you!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/1.0.2

*Thank you for checking out the project, reach out if you have any more suggestions!*

**Comment by julvignola** [comment]
Thank you very much!
