### ISSUE TITLE
Mario Strikers Battle League Football missing !

### ISSUE THREAD

**Issue by Defaalt** [hobby-grade/Nintendo-Switch-Discord-Status#55]
Can someone please add Mario Strikers Battle League Football ! 
Thank you !!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/1.0.3

*Thank you for checking out the project, reach out if you have any more suggestions!*
