### ISSUE TITLE
Add game?

### ISSUE THREAD

**Issue by andrewjhardin** [hobby-grade/Nintendo-Switch-Discord-Status#60]
Could you add Captain Toad: Treasure Tracker and Death And Taxes to the list?

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/1.0.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
