### ISSUE TITLE
Add games?

### ISSUE THREAD

**Issue by dotwavisito** [hobby-grade/Nintendo-Switch-Discord-Status#64]
- Azure Striker Gunvolt 3
- Live A Live

Thank you!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/1.0.4

*Thank you for checking out the project, reach out if you have any more suggestions!*
