### ISSUE TITLE
Add Game 

### ISSUE THREAD

**Issue by Losothelegend** [hobby-grade/Nintendo-Switch-Discord-Status#65]
Xenoblade chronicles 3, thank you

**Comment by GallantForces** [comment]
Second this!

**Comment by Feonyx0** [comment]
Third this

**Comment by Famitsu46** [comment]
Plis add Xeno 3 and Digimon Survive

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/1.0.5

*Thank you for checking out the project, reach out if you have any more suggestions!*

**Comment by Famitsu46** [comment]
tysm!
