### ISSUE TITLE
Add missing game to list

### ISSUE THREAD

**Issue by PlasticTaco** [hobby-grade/Nintendo-Switch-Discord-Status#74]
Can you add "DRAGON QUEST XI S: Echoes of an Elusive Age - Definitive Edition" or some variation of Dragon Quest XI? Thanks!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/1.0.7

*Thank you for checking out the project, reach out if you have any more suggestions!*

**Comment by Tonixov** [comment]
Plz add "Need For Speed™ Hot Pursuit Remastered" and "SUPERHOT" :)
