### ISSUE TITLE
Discord status not showing

### ISSUE THREAD

**Issue by Rellams** [hobby-grade/Nintendo-Switch-Discord-Status#76]
I press submit and nothing happens

**Comment by Rellams** [comment]
Y

I am using windows 10 

Discord: Stable 149043 (f81912b) Host 1.0.9006 Windows 10 64-Bit (10.0.19044)    (sorry ngl im really bad with tech stuff so im just sending u the whole lot)

The latest version of your app

**Comment by hobby-grade** [comment]
Okay, so from what I can test on my end with the Windows client, it looks like the game will update, but something is causing a delay in updating the status on discord. Can you try to update your status and then wait a bit and see if it actually does change?

**Comment by hobby-grade** [comment]
I have fixed the bug you mentioned in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.0

*Thank you for checking out the project, reach out if you have any more suggestions!*
