### ISSUE TITLE
Add Game: NieR:Automata The End of YoRHa Edition

### ISSUE THREAD

**Issue by dotwavisito** [hobby-grade/Nintendo-Switch-Discord-Status#78]
Hello,

Could you please add NieR:Automata: The End of YoRHa Edition to the game list?

Thank you.

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.0

*Thank you for checking out the project, reach out if you have any more suggestions!*
