### ISSUE TITLE
Just Dance 2022

### ISSUE THREAD

**Issue by gothicdollface** [hobby-grade/Nintendo-Switch-Discord-Status#8]
Could you add Just Dance 2022, please? Thank you! :)

**Comment by hobby-grade** [comment]
I will add this game in a release that I push on December 24th!

**Comment by veleini** [comment]
Wondering if it has still released

**Comment by hobby-grade** [comment]
It's late, but here is the release! https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/0.9.0.1
