### ISSUE TITLE
Adding Pokemon Mystery Dungeon DX

### ISSUE THREAD

**Issue by azurajae** [hobby-grade/Nintendo-Switch-Discord-Status#81]
Hi, could you add [Pokémon Mystery Dungeon: Rescue Team DX](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Mystery_Dungeon:_Rescue_Team_DX)? Thanks very much!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.1

*Thank you for checking out the project, reach out if you have any more suggestions!*

**Comment by azurajae** [comment]
Thank you!!
