### ISSUE TITLE
Adding Persona 5 Royal

### ISSUE THREAD

**Issue by alchemical-Apocalypse** [hobby-grade/Nintendo-Switch-Discord-Status#83]
any chance this could be added in light of the new port? thank you very much!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.1

*Thank you for checking out the project, reach out if you have any more suggestions!*
