### ISSUE TITLE
 Add Monster Hunter Generations Ultimate

### ISSUE THREAD

**Issue by SirAvogadro** [hobby-grade/Nintendo-Switch-Discord-Status#84]
can you add Monster Hunter Generations Ultimate please ?

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.1

*Thank you for checking out the project, reach out if you have any more suggestions!*
