### ISSUE TITLE
Preemptively add Bayonetta 3

### ISSUE THREAD

**Issue by dotwavisito** [hobby-grade/Nintendo-Switch-Discord-Status#85]
Bayonetta 3 comes out 10/28. Could it be added in the next update if it is done before then? Thank you.

PS - Also seconding for Persona 5 Royal to be added as someone else suggested.

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.1

*Thank you for checking out the project, reach out if you have any more suggestions!*

**Comment by tio8** [comment]
add sonic frontiers please
