### ISSUE TITLE
Add Mario + Rabbids: Sparks of Hope and Oxenfree

### ISSUE THREAD

**Issue by dotwavisito** [hobby-grade/Nintendo-Switch-Discord-Status#88]
As the title states, thank you so much!

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.2

*Thank you for checking out the project, reach out if you have any more suggestions!*
