### ISSUE TITLE
WorldNeverland - Elnea Kingdom

### ISSUE THREAD

**Issue by arcanaofaegis** [hobby-grade/Nintendo-Switch-Discord-Status#89]
Hello, I was wondering if you'd be kind enough to add the game listed in the title. I'd really appreciate it, thank you! :)

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.2

*Thank you for checking out the project, reach out if you have any more suggestions!*
