### ISSUE TITLE
Please add this new game

### ISSUE THREAD

**Issue by PlasticTaco** [hobby-grade/Nintendo-Switch-Discord-Status#94]
"Tactics Ogre: Reborn" just came out. Appreciate if added. Thanks

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.2

*Thank you for checking out the project, reach out if you have any more suggestions!*
