### ISSUE TITLE
Please add Ni No Kuni : Wrath of the white witch and Ni no kuni : revenant kingdom

### ISSUE THREAD

**Issue by Pheonyxe** [hobby-grade/Nintendo-Switch-Discord-Status#96]

**Comment by hobby-grade** [comment]
I have added the game(s) you requested in the most recent release: https://github.com/hobby-grade/Nintendo-Switch-Discord-Status/releases/tag/v1.1.2

*Thank you for checking out the project, reach out if you have any more suggestions!*
